# Generated by Django 2.2 on 2019-12-18 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
        ('photo_app', '0002_auto_20191218_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment', models.TextField()),
                ('timestamp1', models.DateTimeField(auto_now=True)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserModel', unique=True)),
                ('parentpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_app.PhotoModel', unique=True)),
            ],
        ),
    ]
