# Generated by Django 2.2 on 2019-12-19 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0003_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserModel'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='parentpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_app.PhotoModel'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.UserModel'),
        ),
    ]
