# Generated by Django 2.2 on 2019-12-22 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0004_auto_20191219_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='parentpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='photo_app.PhotoModel'),
        ),
    ]
